"""adca

Revision ID: 04ca8400f4f3
Revises: a62e9654171d
Create Date: 2023-06-13 14:26:18.639266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04ca8400f4f3'
down_revision = 'a62e9654171d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('income_status', sa.Boolean(), nullable=True))
    op.drop_column('orders', 'discount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('discount', mysql.DOUBLE(asdecimal=True), nullable=True))
    op.drop_column('orders', 'income_status')
    # ### end Alembic commands ###
