"""salom

Revision ID: 1c7e79340ec8
Revises: 670940653ace
Create Date: 2023-05-23 17:02:43.075839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7e79340ec8'
down_revision = '670940653ace'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
