"""sss

Revision ID: 39ca21bddb59
Revises: 4b91f7866f6f
Create Date: 2023-06-07 19:30:54.712987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39ca21bddb59'
down_revision = '4b91f7866f6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
