"""bbb

Revision ID: 47ddc6410773
Revises: b4e518ef824d
Create Date: 2023-06-27 14:41:40.881720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47ddc6410773'
down_revision = 'b4e518ef824d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kassas', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kassas', sa.Column('comment', mysql.VARCHAR(length=999), nullable=True))
    # ### end Alembic commands ###
