"""sss

Revision ID: 4b91f7866f6f
Revises: 89888784639b
Create Date: 2023-06-07 16:01:58.192259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b91f7866f6f'
down_revision = '89888784639b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('updelstatus', sa.Boolean(), nullable=True))
    op.add_column('incomes', sa.Column('updelstatus', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'updelstatus')
    op.drop_column('expenses', 'updelstatus')
    # ### end Alembic commands ###
