"""ccc

Revision ID: 670940653ace
Revises: 
Create Date: 2023-05-23 17:01:18.089386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670940653ace'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
