"""abdullajon

Revision ID: 69470afc6fb4
Revises: 45330572d3a3
Create Date: 2023-07-20 18:08:00.088099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69470afc6fb4'
down_revision = '45330572d3a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'materials', 'collactions', ['collaction_id'], ['id'])
    op.add_column('orders', sa.Column('discount', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    # ### end Alembic commands ###
