"""admowdsj

Revision ID: 709695e0d8da
Revises: 835a4ec73388
Create Date: 2023-07-28 16:17:51.797325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709695e0d8da'
down_revision = '835a4ec73388'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.add_column('supplies', sa.Column('cell_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplies', 'cell_id')
    op.drop_column('supplies', 'warehouse_id')
    # ### end Alembic commands ###
