"""aaaa

Revision ID: 72dd48422955
Revises: 
Create Date: 2023-06-13 17:23:14.492375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dd48422955'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('branch_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cells', 'branch_id')
    # ### end Alembic commands ###
