"""salom

Revision ID: 8d7400a64251
Revises: e508c11dbf1f
Create Date: 2023-05-24 18:18:12.786566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7400a64251'
down_revision = 'e508c11dbf1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('width', sa.Numeric(), nullable=True))
    op.add_column('supplies', sa.Column('height', sa.Numeric(), nullable=True))
    op.add_column('warehouse_materials', sa.Column('width', sa.Numeric(), nullable=True))
    op.add_column('warehouse_materials', sa.Column('height', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse_materials', 'height')
    op.drop_column('warehouse_materials', 'width')
    op.drop_column('supplies', 'height')
    op.drop_column('supplies', 'width')
    # ### end Alembic commands ###
