"""bbb

Revision ID: ac41d0a4290f
Revises: acc3b1eab919
Create Date: 2023-05-13 14:24:13.133624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac41d0a4290f'
down_revision = 'acc3b1eab919'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
