"""aaa

Revision ID: acc3b1eab919
Revises: 
Create Date: 2023-05-13 14:16:49.363775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc3b1eab919'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=999), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kassa_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=999), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kassas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=999), nullable=True),
    sa.Column('comment', sa.String(length=999), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=999), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('kassas')
    op.drop_table('incomes')
    # ### end Alembic commands ###
