"""acac

Revision ID: b3fc16c243d9
Revises: 72dd48422955
Create Date: 2023-06-20 14:13:30.850307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3fc16c243d9'
down_revision = '72dd48422955'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standart_mechanisms', 'width')
    op.drop_column('trade_mechanisms', 'width')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_mechanisms', sa.Column('width', mysql.DOUBLE(asdecimal=True), nullable=True))
    op.add_column('standart_mechanisms', sa.Column('width', mysql.DOUBLE(asdecimal=True), nullable=True))
    # ### end Alembic commands ###
