"""boburali

Revision ID: cbc0fdf8e138
Revises: fb7feeb57658
Create Date: 2023-07-28 16:34:20.032488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc0fdf8e138'
down_revision = 'fb7feeb57658'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
