"""cnsjcnj

Revision ID: ec5a17a6ded8
Revises: 69470afc6fb4
Create Date: 2023-07-24 17:10:19.352751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5a17a6ded8'
down_revision = '69470afc6fb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
