"""admowdsjxs

Revision ID: fb7feeb57658
Revises: 709695e0d8da
Create Date: 2023-07-28 16:33:29.986982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7feeb57658'
down_revision = '709695e0d8da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
