from db import Base
from models.phones import Phones
from models.users import Users
from models.categories import Categories
from models.cells import Cells
from models.collactions import Collactions
from models.currencies import Currencies
from models.materials import Materials
from models.mechanisms import Mechanisms
from models.prices import Prices
from models.stage_users import Stage_users
from models.stages import Stages
from models.supplier_balances import Supplier_balances
from models.suppliers import Suppliers
from models.supplies import Supplies
from models.warehouse_materials import Warehouse_materials
from models.warehouses import Warehouses
from models.customers import Customers
from models.discounts import Discounts
from models.orders import Orders
from models.incomes import Incomes
from models.expenses import Expenses
from models.kassas import Kassas
from models.trades import Trades
from models.trade_mechanisms import Trade_mechanisms
from models.standart_mechanisms import Standart_mechanisms
from models.loans import Loans
from models.uploaded_files import Uploaded_files
